### ISSUE TITLE
[1.19.2] Straight flowers are not tagged as flowers 

### ISSUE THREAD

**Issue by TelepathicGrunt** [GeheimagentNr1/ManyIdeasCore#1]
Hello, on 1.19.2 Forge with latest ManyIdeas Core, the straight flowers from the mod are not tagged as `minecraft:small_flowers` or `minecraft:tall_flowers`. This means that bees cannot pollinate these flowers, saplings grown next to them do not have chance for beehive, and enderment cannot pick up the small flowers. It also means less compat with other mods that do check these tags
https://minecraft.fandom.com/wiki/Tag#blocks_small_flowers
https://minecraft.fandom.com/wiki/Tag#blocks_tall_flowers

Just a small thing to add to add functionality to the flowers to match the vanilla versions out of the box. Also don't forget the item form of these tags so they can be used to breed bees!

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Implemented</td></tr><tr><th>Issue type:</th><td>Bug</td></tr><tr><th>Fix type:</th><td>New feature</td></tr><tr><th>Fix version:</th><td>1.4.1</td></tr><tr><th>Fix release date:</th><td>10.04.23</td></tr></tbody></table>

**TODOs:**

*   [x] Added tags for 1.18.2, 1.19.2, 1.19.4
