### ISSUE TITLE
Rainbow Terrocatta

### ISSUE THREAD

**Issue by saphsara** [GeheimagentNr1/ManyIdeasCore#2]
**Versions**
Minecraft Version: 1.19.2
Minecraft Forge Version: 43.2.10
Mod Version: 1.19.2 - 1.0.0

**Log files**

**Describe the bug**
Is the rainbow Terrocatta suppuse to change colors , if so it is not they are only white
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
I was expecting it to change colors 

**Screenshots**

**Additional context**

![Screenshot 2023-07-14 220636](https://github.com/GeheimagentNr1/ManyIdeasCore/assets/33788318/1a3c67f1-b74d-405a-88fa-68ed73aea34f)

**Comment by GeheimagentNr1** [comment]
Rainbow Terracotta is intended to be a real white, because White Terracotta is not a real white.  
Details can be found here: https://secretsoft.de/mods/manyideas-core/core-building-blocks/rainbow-terracotta/

**Comment by saphsara** [comment]
thank you
