### ISSUE TITLE
Dye Crafting Table only accepts blocks that are already dyed.

### ISSUE THREAD

**Issue by DMSledge** [GeheimagentNr1/ManyIdeasCore#5]
### Minecraft Version

1.20.1

### Minecraft Forge Version

47.2

### Mod Version

1.20.1

### Describe the bug

Pretty simple. I cannot make any coloured wood or planks as the only valid recipes in the dye crafting table require already coloured items.

### Expected behavior

Planks to be dyed.

### Steps to reproduce

Put planks or wood in dye crafting table with a dye.

### References (optional)

JEI agrees that the recipe doesn't exist.

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Won't fix (cannot be reproduced)</td></tr><tr><th>Issue type:</th><td>None</td></tr><tr><th>Fix type:</th><td>None</td></tr><tr><th>Fix version:</th><td>None</td></tr><tr><th>Fix release date:</th><td>None</td></tr></tbody></table>

**Issue confirmed for:**

**None**

**TODOs:**

*   [x] Test with Minecraft 1.20.1, Forge 47.2.0 and Mod version 1.4.2, if "Colored Planks" and "Colored Wood" can be crafted.

**Comment by GeheimagentNr1** [comment]
For the "Colored Planks" you need "Seamless Planks" and for "Colored Wood" you can use "Wood", "Stripped Wood" or "Smooth Stripped Wood". I tested the recipes and they are working.
