### ISSUE TITLE
Copper Plate

### ISSUE THREAD

**Issue by LTAxe42** [GeheimagentNr1/ManyIdeasCore#7]
### Minecraft Version

1.20.4

### Minecraft Forge Version

49.0.31

### Mod Version

1.20.4

### Describe the bug

When placing a copper block into the diamond table saw, I am not able to make copper plates. 

### Expected behavior

Expect a copper plate to be made

### Steps to reproduce

Copper block
Raw copper block

**Comment by GeheimagentNr1** [comment]
Copper plates can only be made out of "Waxed Block of Copper".
